---
- hosts: linux:children
  tasks:
    - name: Installer Apache & Php7
      ansible.builtin.apt: name=apache2 state=present
      loop:
      - apache2
      - libapache2-mod-php7.4
      when: ansible_facts['os_family'] == 'Debian'

    - name: Démarrer le service Apache
      ansible.builtin.service: name=apache2 state=started enabled=true
      when: ansible_facts['os_family'] == 'Debian'

    - name: copier un phpinfo
      ansible.builtin.copy: src=info.php dest=/var/www/html/index.php owner=www-data group=www-data mode=0664
      when: ansible_facts['os_family'] == 'Debian'
      
    - name: Template configuration file
      ansible.builtin.template:
        src: ports.j2
        dest: /etc/apache2/ports.conf
      notify:
        - Restart apache
      when: ansible_facts['os_family'] == 'Debian'

    - name: Installer Httpd
      ansible.builtin.dnf:
        name=httpd state=present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Installer Php7
      ansible.builtin.dnf:
        name=php state=present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Démarrer le service Httpd
      ansible.builtin.service:
        name=httpd state=started enabled=true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: copier un phpinfo
      ansible.builtin.copy:
        src=info.php dest=/var/www/html/index.php owner=apache group=apache mode=0664
      when: ansible_facts['os_family'] == 'RedHat'

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted

  vars_files:
    - firewall.yaml
  roles :
    - { role: geerlingguy.firewall }